<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>notes</string>
	</array>
	<key>name</key>
	<string>Notes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\[)(actionscript|as)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Actionscript</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|actionscript|as))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.actionscript.2</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(applescript)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Applescript</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|applescript))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.applescript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(asp|asa)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ASP</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|asp|asa))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.asp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(c)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>C</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|c))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(cs|c#|csharp)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>C#</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|cs|c#|csharp))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(c++|cpp|cc|cxx)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>C++</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|c++|cpp|cc|cxx))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(clj|clojure)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Clojure</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|clj|clojure))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.clojure</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(css)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>CSS</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|css))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(di)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>D</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|di))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.d</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(erl|hrl|Emakefile|emakefile|)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Erlang</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|erl|hrl|Emakefile|emakefile|))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.erlang</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(go|golang)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Go</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|go|golang))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(groovy|gvy)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Groovy</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|groovy|gvy))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.groovy</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(hs|haskell)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Haskell</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|hs|haskell))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(html|htm|shtml|xhtml|phtml|inc|tmpl|tpl|ctp)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>HTML</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|html|htm|shtml|xhtml|phtml|inc|tmpl|tpl|ctp))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(java|bsh)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Java</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|java|bsh))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(js|jsx|htc|javascript)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Javascript</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|js|jsx|htc|javascript))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(lua)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Lua</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|lua))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lua</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(gnumakefile|makefile|makefile|ocamlmakefile|make)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Makefile</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|gnumakefile|makefile|makefile|ocamlmakefile|make))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.makefile</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(mdown|markdown|markdn|md)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Markdown</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|mdown|markdown|markdn|md))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(matlab)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matlab</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|matlab))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.matlab</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(objective-c|objc|m|h)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Objective-c</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|objective-c|objc|m|h))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.objc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(ocaml|ml|mli)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Ocaml</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|ocaml|ml|mli))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ocaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(p|pas|pascal)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Pascal</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|p|pas|pascal))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.pascal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(pm|pl|pod|t|perl)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Perl</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|pm|pl|pod|t|perl))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(php)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PHP</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|php))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(cpy|py|python|rpy|pyw)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Python</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|cpy|py|python|rpy|pyw))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(r|s|rprofile)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>R</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|r|s|rprofile))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(re|regex|regexp)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Regex</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|re|regex|regexp))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(rb|rbx|rjs|ruby|Rakefile|rake|cgi|fcgi|gemspec|irbrc|capfile|gemfile)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Ruby</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|rb|rbx|rjs|ruby|Rakefile|rake|cgi|fcgi|gemspec|irbrc|capfile|gemfile))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(scala)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Scala</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|scala))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(sh|bash|zsh|bashrc)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Shell</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|sh|bash|zsh|bashrc))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(sql|dml|ddl|mysql)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>SQL</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|sql|dml|ddl|mysql))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(tcl)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>TCL</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|tcl))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.tcl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(tex|latex|sty|cls)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>TeX</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|tex|latex|sty|cls))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(xml|tld|jsp|pt|cpt|dtml|rss|opml)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>XML</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|xml|tld|jsp|pt|cpt|dtml|rss|opml))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(xsl|xslt)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>XSL</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|xsl|xslt))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml.xsl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)(yaml|yml)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>YAML</string>
			<key>end</key>
			<string>(\[)(\\?\/?(end|yaml|yml))(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.notes</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.notes</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Urls</string>
			<key>match</key>
			<string>(([a-zA-Z]{3,6}3?\:\/\/)?([-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&amp;//=]*)))</string>
			<key>name</key>
			<string>support.class.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>(?&lt;!\:)(\/\/.*)</string>
			<key>name</key>
			<string>comment.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line breaks</string>
			<key>match</key>
			<string>^(\-[\-\=]{2}.*)</string>
			<key>name</key>
			<string>support.function.notes</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Ordered bullets</string>
			<key>match</key>
			<string>^([ \t]*[0-9a-z]+[\:\.\)]\)?\s(\w+\:)?)</string>
			<key>name</key>
			<string>keyword.operator.notes</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Unordered bullets</string>
			<key>match</key>
			<string>^(\t*[\-\=\.]+\s(\w+\:)?)</string>
			<key>name</key>
			<string>variable.language.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Emphasis</string>
			<key>match</key>
			<string>(\*+[a-zA-Z \t]+\*+)</string>
			<key>name</key>
			<string>keyword.other.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Arrows</string>
			<key>match</key>
			<string>(-+&gt;||=+&gt;||&lt;=+||&lt;-+)</string>
			<key>name</key>
			<string>variable.language.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Important, surrounded by &lt;...&gt;</string>
			<key>match</key>
			<string>(\&lt;[^\&gt;]*\&gt;)</string>
			<key>name</key>
			<string>constant.other.date.notes</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.notes</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Highlights</string>
			<key>match</key>
			<string>^[^\#]*(\#+[^\#]*\#*)</string>
			<key>name</key>
			<string>nothing.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Headers</string>
			<key>match</key>
			<string>^([A-Z].*\:)$</string>
			<key>name</key>
			<string>entity.name.tag.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Proper headers</string>
			<key>match</key>
			<string>^([-=]+\s?\w[\w\s]*[\-=]+)</string>
			<key>name</key>
			<string>entity.name.tag.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single Quotes</string>
			<key>match</key>
			<string>(\'[^\']*\')</string>
			<key>name</key>
			<string>string.quoted.single.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Double Quotes</string>
			<key>match</key>
			<string>(\"[^\"]*\")</string>
			<key>name</key>
			<string>string.quoted.double.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Warning/critical</string>
			<key>match</key>
			<string>(?![a-zA-Z])\!+[^\!\n\r]+\!*</string>
			<key>name</key>
			<string>invalid.deprecated.notes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Emphasis on parentheses</string>
			<key>match</key>
			<string>([\(\)])</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Top-level vocab definitions</string>
			<key>match</key>
			<string>^((\w+\s?\w*\:)(?=[ \t][\w\d]))</string>
			<key>name</key>
			<string>keyword.other.notes</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.notes</string>
	<key>uuid</key>
	<string>b9bf3970-f517-46fd-a7f8-ae78fd761f84</string>
</dict>
</plist>
